name: Application-Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened , synchronize , reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Test
        run: ./gradlew test --info