name: Application-Test
on:
  pull_request:
    types: [ closed ]

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: notify-merged-pr
        if: github.event.pull_request.merged == 'true'
        run: echo ${{ github.event.pull_request.title }}
