name: pr-merged-notify
on:
  pull_request:
    types: [ closed ]

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: notify-echo
        run: echo ${{ github.event.pull_request }}
