name: pr-merged-notify
on:
  pull_request:
    types: [ opened , synchronize , reopened, closed ]

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: notify-slack
        if: github.event.pull_request.merged == true
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: good
          SLACK_TITLE: deploy
          SLACK_MESSAGE: '${{ github.event.pull_request.title }} merged & deploy start!! :rocket:'
      - name: notify-echo
        run: |
          echo ${{ github.event.pull_request.merged }}
          echo ${{ github.event.pull_request.title }}
