name: pr-merged-notify
on:
  pull_request:
    types: [ opened , synchronize , reopened, closed ]

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: notify-slack
        if: github.event.pull_request.merged == true
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: good
          SLACK_USERNAME: 배포알림요정
          SLACK_TITLE: 배포 알림
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: |
            @channel PR merged & deploy start!! :rocket:
            PR명 : ${{ github.event.pull_request.title }}
            PR링크: (${{ github.event.pull_request.html_url }})
      - name: notify-echo
        run: |
          echo ${{ github.event.pull_request.merged }}
          echo ${{ github.event.pull_request.title }}
